### ISSUE TITLE
index

### ISSUE THREAD

**Issue by Wellinton-07** [edwintantawi/clone-app__airbnb#1]
where file index.html

**Comment by edwintantawi** [comment]
Hi @Wellinton-07, for this project created using the **[NextJS](https://nextjs.org/)** Framework, which doesn't need a static file index.html because it will generate all static html files based on the components in the "pages" folder, you can look into /pages/_document.tsx for the document structure, and all file inside pages folder without underscore prefix should be a page. Thank you.
